link_news: "http://news.railstutorial.org/"
link_contact: "http://www.railstutorial.org/#contact"
link_rails: "http://www.railstutorial.org/"
link_author: "http://www.michealhartl.com/"
link_help: "http://www.railstutorial.org/help"
